name: zed-online # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.3.2' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A remake of the classic strategy game Commander Zod (or just Z).
description: |
  Over the last 10 years or so, several projects have been started to bring back Commander Zod to live on modern technology. One of them was the Zod Engine by FreakNigh (Nighsoft). The Zod Engine is a great contribution to the community and brought us all back to those days again. Based on the Zod Engine, DaMarkov started a fork called “Zed Online” and continued the development by adding a user interface, online multiplayer support and much more. Other contributors, including the ZZone, joined DaMarkov in his endeavor to bring back the game to the fans. And back it is!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  zed-online_icon.png
title: Zed Online

apps:
  zed-online:
    command: "./ZED Online"
  zed-online-server:
    command: "./ZED Online Server"
  zed-online-updater:
    command: "./ZED Online Updater"
parts:
  zed-online:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      zed-online: build/
      zed-online.1: man/man1/

architectures:
  - build-on: amd64

